namespace PharmacyAPI.Models
{
    public class WebsiteVisit
    {
        public long Id { get; set; }

        // Anonymous ID generated by the frontend
        public string VisitorId { get; set; } = null!;

        public DateTime VisitedAt { get; set; }
    }
}
